/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quienquieresermillonariofinal.ADMINISTRADORES;

import java.io.File;
import javax.swing.*; //Libreria que nos permite trabajar con elementos de un JFrame
/**
 *
 * @author USER
 */
public class Administrador extends javax.swing.JFrame {
    
     JFileChooser seleccionado = new JFileChooser(); //Objeto tipo Chooser
     File preguntas; //Fichero preguntas
     GestionAdministradores gestionarpreguntas = new GestionAdministradores(); //Objeto de la clase "GestionAdministradores"
    /**
     * Creates new form Administrador
     */
    public Administrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtAreaPreguntas = new javax.swing.JTextArea();
        btnAbrirPreguntas = new javax.swing.JButton();
        btnGuardarPreguntas = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");

        txtAreaPreguntas.setColumns(20);
        txtAreaPreguntas.setRows(5);
        jScrollPane1.setViewportView(txtAreaPreguntas);

        btnAbrirPreguntas.setText("Abrir Preguntas");
        btnAbrirPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirPreguntasActionPerformed(evt);
            }
        });

        btnGuardarPreguntas.setText("Guardar / Modificar Preguntas");
        btnGuardarPreguntas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarPreguntasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAbrirPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGuardarPreguntas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnAbrirPreguntas)
                .addGap(18, 18, 18)
                .addComponent(btnGuardarPreguntas)
                .addContainerGap(254, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    //Al presionar el botón "Abrir Preguntas".
    private void btnAbrirPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirPreguntasActionPerformed
        
        if (seleccionado.showDialog(null, "Abrir Preguntas") == JFileChooser.APPROVE_OPTION){ //El "null" posiciona la ventana en la parte del centro, y el titulo a mostrar. Es decir, si seleccionamos un archivo se ejecuta lo siguiente:
        
            preguntas = seleccionado.getSelectedFile(); //Al archivo le damos el valor de seleccionado.
            if (preguntas.canRead()){   //En caso de que ese archivo se puede leer.
            
                if (preguntas.getName().endsWith("txt")){ //Pregunta si es un archivo de texto, osea extención txt.
                    
                    String contenido = gestionarpreguntas.AbrirPreguntas(preguntas); //Le mandamos el archivo seleccionado para la apertura.
                    txtAreaPreguntas.setText(contenido); //Nos regresa el contenido y se pone dentro del Text Area.
                }else{
                    
                    JOptionPane.showMessageDialog(null, "Por favor seleccione un archivo de texto."); //En caso de que no sea un archivo .txt
                    
                }
            }
            
        }
        
    }//GEN-LAST:event_btnAbrirPreguntasActionPerformed

    //Al presionar el botón "Guardar Preguntas".
    private void btnGuardarPreguntasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarPreguntasActionPerformed
        
        if(seleccionado.showDialog(null, "Guardar Preguntas") == JFileChooser.APPROVE_OPTION){
            preguntas = seleccionado.getSelectedFile();
            if(preguntas.getName().endsWith("txt")){ //Si el archivo es .txt se crea como una variable de respuesta a la que se le designa el valor que se recupere de "Guardar Preguntas"
                String contenido = txtAreaPreguntas.getText(); //Se le designa el valor que se recupere del Text Area.
                String respuesta = gestionarpreguntas.GuardarPreguntas(preguntas, contenido); //Le enviamos "contenido"
                if(respuesta!=null){ //Si es diferente de "null"
                    JOptionPane.showMessageDialog(null, respuesta);
                }else{
                    JOptionPane.showMessageDialog(null, "Error al guardar las preguntas."); //En caso de error.
                }
            }else{ //En caso de que no sea el archivo de extención .txt
                JOptionPane.showMessageDialog(null, "Las preguntas se deben guardar en un formato de texto.");
            }
        }
    }//GEN-LAST:event_btnGuardarPreguntasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrirPreguntas;
    private javax.swing.JButton btnGuardarPreguntas;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAreaPreguntas;
    // End of variables declaration//GEN-END:variables
}
